// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABcjmh3bUGkZJ2D3CwwX4XCTgTtDMNuxM',
    appId: '1:800459369267:web:dd9cfa514a8b78353fac46',
    messagingSenderId: '800459369267',
    projectId: 'saadoun-3da37',
    authDomain: 'saadoun-3da37.firebaseapp.com',
    storageBucket: 'saadoun-3da37.appspot.com',
    measurementId: 'G-ER8MQG8MGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp-uZLARYeAg8-bsAfokXTUpahUofP8Nk',
    appId: '1:800459369267:android:60ba8ea5f8310aaf3fac46',
    messagingSenderId: '800459369267',
    projectId: 'saadoun-3da37',
    storageBucket: 'saadoun-3da37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcJgJQw8yGQXxmcV2_fVo2FpalvPmM35Y',
    appId: '1:800459369267:ios:3dbd3a354a3833cb3fac46',
    messagingSenderId: '800459369267',
    projectId: 'saadoun-3da37',
    storageBucket: 'saadoun-3da37.appspot.com',
    iosBundleId: 'com.example.saadoun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcJgJQw8yGQXxmcV2_fVo2FpalvPmM35Y',
    appId: '1:800459369267:ios:3dbd3a354a3833cb3fac46',
    messagingSenderId: '800459369267',
    projectId: 'saadoun-3da37',
    storageBucket: 'saadoun-3da37.appspot.com',
    iosBundleId: 'com.example.saadoun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABcjmh3bUGkZJ2D3CwwX4XCTgTtDMNuxM',
    appId: '1:800459369267:web:42ce08ac8447a6eb3fac46',
    messagingSenderId: '800459369267',
    projectId: 'saadoun-3da37',
    authDomain: 'saadoun-3da37.firebaseapp.com',
    storageBucket: 'saadoun-3da37.appspot.com',
    measurementId: 'G-K9G7435E5W',
  );
}
